services:
  client:
    image: zcodeapp/nodejs
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    command: /bin/bash
    user: node
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ~/.gitconfig:/home/node/.gitconfig
      - ${PWD}:/app
    networks:
      - public
  test:
    image: zcodeapp/nodejs
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    entrypoint: /usr/local/bin/npm
    command: run test
    user: node
    volumes:
      - ~/.ssh:/home/node/.ssh
      - /var/www/msexpandable:/app
    environment:
      - NODE_ENV=development
    ports:
      - 9229:9229
    networks:
      - public

networks:
  public:
    driver: bridge